import { Box, Divider, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
function InvoicePrint({business={},invoice={},customer={},items=[]}){
 const subtotal=Number(invoice.subtotal||0),gstAmount=Number(invoice.gst_amount||0),grandTotal=Number(invoice.total_amount||0);
 const totalMrp=Number(invoice.total_mrp||items.reduce((s,i)=>s+Number(i.mrp||i.rate||0)*Number(i.quantity||0),0));
 const saving=Number(invoice.total_saving||Math.max(totalMrp-subtotal,0));
 return <Box className="invoice-print-area" sx={{backgroundColor:"#fff",color:"#000",width:"100%",p:3}}>
 <Box textAlign="center" mb={2}><Typography variant="h4" fontWeight={800}>{business.business_name||"Business Name"}</Typography><Typography variant="body2">{business.address||""}</Typography><Typography variant="body2">GSTIN: {business.gst_number||"-"}</Typography><Typography variant="body2">{business.mobile||""}{business.email?` | ${business.email}`:""}</Typography></Box><Divider sx={{my:2}}/>
 <Box sx={{display:"flex",justifyContent:"space-between",gap:2,mb:2}}><Box><Typography fontWeight={700}>Bill To</Typography><Typography>{customer.customer_name||"-"}</Typography><Typography variant="body2">Mobile: {customer.mobile||"-"}</Typography></Box><Box textAlign="right"><Typography fontWeight={700}>Invoice No: {invoice.invoice_number||"-"}</Typography><Typography variant="body2">Date: {invoice.bill_date||"-"}</Typography><Typography variant="body2">Payment: {invoice.payment_mode||"-"}</Typography></Box></Box>
 <Table size="small" sx={{border:"1px solid #000","& th, & td":{border:"1px solid #000",px:1}}}><TableHead><TableRow><TableCell>Item</TableCell><TableCell align="right">Qty</TableCell><TableCell align="right">MRP</TableCell><TableCell align="right">Sales</TableCell><TableCell align="right">Save</TableCell><TableCell align="right">GST</TableCell><TableCell align="right">Amount</TableCell></TableRow></TableHead><TableBody>{items.map((item,index)=>{const qty=Number(item.quantity||0),mrp=Number(item.mrp||item.rate||0),rate=Number(item.sale_price||item.rate||0),lineSaving=Math.max((mrp-rate)*qty,0);return <TableRow key={item.id||`${item.item_name}-${index}`}><TableCell>{item.item_name||"-"}</TableCell><TableCell align="right">{qty}</TableCell><TableCell align="right">₹{mrp.toFixed(2)}</TableCell><TableCell align="right">₹{rate.toFixed(2)}</TableCell><TableCell align="right">₹{lineSaving.toFixed(2)}</TableCell><TableCell align="right">{Number(item.gst_percent||0).toFixed(2)}%</TableCell><TableCell align="right">₹{Number(item.amount||0).toFixed(2)}</TableCell></TableRow>})}{!items.length&&<TableRow><TableCell colSpan={7} align="center">No invoice items</TableCell></TableRow>}</TableBody></Table>
 <Box sx={{width:320,ml:"auto",mt:3}}><Box display="flex" justifyContent="space-between" mb={1}><Typography>Total MRP</Typography><Typography>₹{totalMrp.toFixed(2)}</Typography></Box><Box display="flex" justifyContent="space-between" mb={1}><Typography>Sales Subtotal</Typography><Typography>₹{subtotal.toFixed(2)}</Typography></Box><Box display="flex" justifyContent="space-between" mb={1}><Typography>GST</Typography><Typography>₹{gstAmount.toFixed(2)}</Typography></Box><Box display="flex" justifyContent="space-between" mb={1}><Typography fontWeight={800}>You Saved</Typography><Typography fontWeight={800}>₹{saving.toFixed(2)}</Typography></Box><Divider sx={{my:1}}/><Box display="flex" justifyContent="space-between"><Typography variant="h6" fontWeight={800}>Amount Payable</Typography><Typography variant="h6" fontWeight={800}>₹{grandTotal.toFixed(2)}</Typography></Box></Box>
 <Box textAlign="center" mt={4}><Typography variant="h6" fontWeight={900}>You saved ₹{saving.toFixed(2)} on this purchase!</Typography><Typography fontWeight={700} mt={1}>Thank you for your business</Typography><Typography variant="caption">This is a computer-generated invoice.</Typography></Box></Box>
}
export default InvoicePrint;
