import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from "@mui/material";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import HistoryRoundedIcon from "@mui/icons-material/HistoryRounded";
import PaymentsRoundedIcon from "@mui/icons-material/PaymentsRounded";
import AppLayout from "../components/AppLayout";
import PageHeader from "../components/PageHeader";
import { addDealer, addDealerPayment, deleteDealer, getDealerPayments, getDealers } from "../services/api";
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v||0)); const today=()=>new Date().toISOString().slice(0,10);
export default function Dealers(){
 const[dealers,setDealers]=useState([]),[message,setMessage]=useState({type:"",text:""}),[saving,setSaving]=useState(false);
 const[form,setForm]=useState({dealer_name:"",mobile:"",address:"",bill_amount:"",bill_date:today()});
 const[paymentOpen,setPaymentOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[selected,setSelected]=useState(null),[history,setHistory]=useState([]);
 const[payment,setPayment]=useState({paid_amount:"",payment_mode:"Cash",payment_date:today(),reference:"",note:""});
 const load=async()=>{try{setDealers(await getDealers())}catch(e){setMessage({type:"error",text:e.message})}};useEffect(()=>{load()},[]);
 const totals=useMemo(()=>dealers.reduce((a,d)=>({bill:a.bill+Number(d.bill_amount||0),paid:a.paid+Number(d.paid_amount||0),pending:a.pending+Number(d.pending_amount||0)}),{bill:0,paid:0,pending:0}),[dealers]);
 const saveDealer=async()=>{if(!form.dealer_name||!form.bill_amount)return setMessage({type:"warning",text:"Enter dealer name and bill amount."});try{setSaving(true);await addDealer({...form,bill_amount:Number(form.bill_amount)});setForm({dealer_name:"",mobile:"",address:"",bill_amount:"",bill_date:today()});await load();setMessage({type:"success",text:"Dealer record saved."})}catch(e){setMessage({type:"error",text:e.message})}finally{setSaving(false)}};
 const openPayment=d=>{setSelected(d);setPayment({paid_amount:"",payment_mode:"Cash",payment_date:today(),reference:"",note:""});setPaymentOpen(true)};
 const recordPayment=async()=>{if(!payment.paid_amount)return setMessage({type:"warning",text:"Enter payment amount."});try{setSaving(true);await addDealerPayment({dealer_id:selected.id,...payment,paid_amount:Number(payment.paid_amount)});setPaymentOpen(false);await load();setMessage({type:"success",text:"Dealer payment recorded with payment date."})}catch(e){setMessage({type:"error",text:e.message})}finally{setSaving(false)}};
 const showHistory=async d=>{try{setSelected(d);setHistory(await getDealerPayments(d.id));setHistoryOpen(true)}catch(e){setMessage({type:"error",text:e.message})}};
 const remove=async id=>{if(!confirm("Delete dealer and payment history?"))return;try{await deleteDealer(id);await load();setMessage({type:"success",text:"Dealer deleted."})}catch(e){setMessage({type:"error",text:e.message})}};
 return <AppLayout><PageHeader title="Dealers" subtitle="Manage dealer bills, dated payments and payment history" />{message.text&&<Alert severity={message.type} sx={{mb:2.5}}>{message.text}</Alert>}
 <Grid container spacing={2.5} mb={3}>{[["Total purchases",totals.bill],["Total paid",totals.paid],["Outstanding",totals.pending]].map(([l,v])=><Grid key={l} size={{xs:12,sm:4}}><Card><CardContent><Typography variant="body2" color="text.secondary">{l}</Typography><Typography variant="h5" mt={.7}>{money(v)}</Typography></CardContent></Card></Grid>)}</Grid>
 <Grid container spacing={3}><Grid size={{xs:12,lg:4}}><Card><CardContent sx={{p:3}}><Typography variant="h6">Add dealer bill</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5,mb:2.5}}>Record dealer details and purchase bill.</Typography><Stack spacing={2}><TextField label="Dealer Name" value={form.dealer_name} onChange={e=>setForm({...form,dealer_name:e.target.value})}/><TextField label="Mobile" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/><TextField label="Address" multiline rows={2} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><TextField type="number" label="Bill Amount" value={form.bill_amount} onChange={e=>setForm({...form,bill_amount:e.target.value})}/><TextField type="date" label="Bill Date" InputLabelProps={{shrink:true}} value={form.bill_date} onChange={e=>setForm({...form,bill_date:e.target.value})}/><Button variant="contained" onClick={saveDealer} disabled={saving}>{saving?"Saving...":"Save Dealer Bill"}</Button></Stack></CardContent></Card></Grid>
 <Grid size={{xs:12,lg:8}}><Card><CardContent sx={{p:0}}><Box sx={{p:3}}><Typography variant="h6">Dealer summary</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>Record payment and open date-wise payment history.</Typography></Box><TableContainer><Table><TableHead><TableRow><TableCell>Dealer</TableCell><TableCell>Bill Date</TableCell><TableCell align="right">Bill</TableCell><TableCell align="right">Paid</TableCell><TableCell align="right">Outstanding</TableCell><TableCell align="center">Actions</TableCell></TableRow></TableHead><TableBody>{dealers.map(d=><TableRow key={d.id} hover><TableCell><Typography fontWeight={700}>{d.dealer_name}</Typography><Typography variant="caption" color="text.secondary">{d.mobile||"—"}</Typography></TableCell><TableCell>{d.bill_date?new Date(`${d.bill_date}T00:00:00`).toLocaleDateString("en-GB"):"—"}</TableCell><TableCell align="right">{money(d.bill_amount)}</TableCell><TableCell align="right">{money(d.paid_amount)}</TableCell><TableCell align="right"><Typography fontWeight={800} color={Number(d.pending_amount)>0?"error.main":"success.main"}>{money(d.pending_amount)}</Typography></TableCell><TableCell align="center"><Tooltip title="Record Payment"><span><IconButton color="success" disabled={Number(d.pending_amount)<=0} onClick={()=>openPayment(d)}><PaymentsRoundedIcon/></IconButton></span></Tooltip><Tooltip title="Payment History"><IconButton color="primary" onClick={()=>showHistory(d)}><HistoryRoundedIcon/></IconButton></Tooltip><Tooltip title="Delete"><IconButton color="error" onClick={()=>remove(d.id)}><DeleteOutlineRoundedIcon/></IconButton></Tooltip></TableCell></TableRow>)}{!dealers.length&&<TableRow><TableCell colSpan={6}><Box sx={{py:7,textAlign:"center"}}><Typography fontWeight={700}>No dealer records found</Typography></Box></TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card></Grid></Grid>
 <Dialog open={paymentOpen} onClose={()=>setPaymentOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Record dealer payment</DialogTitle><DialogContent><Typography variant="body2" color="text.secondary" sx={{mb:2.5}}>{selected?.dealer_name} · Outstanding {money(selected?.pending_amount)}</Typography><Stack spacing={2}><TextField type="number" label="Payment Amount" value={payment.paid_amount} onChange={e=>setPayment({...payment,paid_amount:e.target.value})}/><TextField type="date" label="Payment Date" InputLabelProps={{shrink:true}} value={payment.payment_date} onChange={e=>setPayment({...payment,payment_date:e.target.value})}/><TextField select label="Payment Mode" value={payment.payment_mode} onChange={e=>setPayment({...payment,payment_mode:e.target.value})}>{["Cash","Online","Bank Transfer","Cheque"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Reference Number" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/><TextField label="Note" multiline rows={2} value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setPaymentOpen(false)}>Cancel</Button><Button variant="contained" onClick={recordPayment} disabled={saving}>Save Payment</Button></DialogActions></Dialog>
 <Dialog open={historyOpen} onClose={()=>setHistoryOpen(false)} fullWidth maxWidth="md"><DialogTitle>Payment history — {selected?.dealer_name}</DialogTitle><DialogContent><TableContainer><Table><TableHead><TableRow><TableCell>Date</TableCell><TableCell>Mode</TableCell><TableCell>Reference</TableCell><TableCell>Note</TableCell><TableCell align="right">Amount</TableCell></TableRow></TableHead><TableBody>{history.map(h=><TableRow key={h.id}><TableCell>{h.payment_date?new Date(h.payment_date).toLocaleDateString("en-GB"):"—"}</TableCell><TableCell><Chip size="small" label={h.payment_mode}/></TableCell><TableCell>{h.reference||"—"}</TableCell><TableCell>{h.note||"—"}</TableCell><TableCell align="right"><Typography fontWeight={800}>{money(h.paid_amount)}</Typography></TableCell></TableRow>)}{!history.length&&<TableRow><TableCell colSpan={5} align="center" sx={{py:5}}>No payment history</TableCell></TableRow>}</TableBody></Table></TableContainer></DialogContent><DialogActions><Button onClick={()=>setHistoryOpen(false)}>Close</Button></DialogActions></Dialog>
 </AppLayout>}
