import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Grid, IconButton, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from "@mui/material";
import AddCardRoundedIcon from "@mui/icons-material/AddCardRounded"; import ReceiptRoundedIcon from "@mui/icons-material/ReceiptRounded"; import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import AppLayout from "../components/AppLayout"; import PageHeader from "../components/PageHeader"; import { addExpense, deleteExpense, getExpenses } from "../services/api";
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v||0)); const currentMonth=()=>new Date().toISOString().slice(0,7);
const bounds=m=>{const[y,mo]=m.split("-").map(Number);return {from:`${m}-01`,to:new Date(y,mo,0).toISOString().slice(0,10)}};
export default function Expense(){const[rows,setRows]=useState([]),[allRows,setAllRows]=useState([]),[month,setMonth]=useState(currentMonth()),[message,setMessage]=useState({type:"",text:""}),[saving,setSaving]=useState(false);const[form,setForm]=useState({expense_name:"",category:"Miscellaneous",amount:"",payment_mode:"Cash",expense_date:new Date().toISOString().slice(0,10),note:""});
 const load=async(selected=month)=>{try{const b=bounds(selected);const [filtered,all]=await Promise.all([getExpenses(b.from,b.to),getExpenses()]);setRows(filtered);setAllRows(all)}catch(e){setMessage({type:"error",text:e.message})}};useEffect(()=>{load()},[]);
 const selectedTotal=useMemo(()=>rows.reduce((s,x)=>s+Number(x.amount||0),0),[rows]);const allTotal=useMemo(()=>allRows.reduce((s,x)=>s+Number(x.amount||0),0),[allRows]);
 const applyMonth=()=>load(month); const reset=()=>{const m=currentMonth();setMonth(m);load(m)};
 const save=async()=>{if(!form.expense_name||!form.amount)return setMessage({type:"warning",text:"Enter expense name and amount."});try{setSaving(true);await addExpense({...form,amount:Number(form.amount)});setForm({...form,expense_name:"",amount:"",note:""});await load();setMessage({type:"success",text:"Expense saved successfully."})}catch(e){setMessage({type:"error",text:e.message})}finally{setSaving(false)}};
 const remove=async id=>{if(!confirm("Delete this expense?"))return;try{await deleteExpense(id);await load();setMessage({type:"success",text:"Expense deleted."})}catch(e){setMessage({type:"error",text:e.message})}};
 return <AppLayout><PageHeader title="Expenses" subtitle="Record expenses and review them month by month" />{message.text&&<Alert severity={message.type} sx={{mb:2.5}}>{message.text}</Alert>}
 <Card sx={{mb:3}}><CardContent sx={{p:3}}><Typography variant="h6">Monthly review</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5,mb:2.5}}>Choose month and year to view previous expense history.</Typography><Grid container spacing={2}><Grid size={{xs:12,md:4}}><TextField fullWidth type="month" label="Month & Year" InputLabelProps={{shrink:true}} value={month} onChange={e=>setMonth(e.target.value)}/></Grid><Grid size={{xs:12,md:4}}><Button fullWidth variant="contained" sx={{height:40}} onClick={applyMonth}>Apply Month</Button></Grid><Grid size={{xs:12,md:4}}><Button fullWidth variant="outlined" sx={{height:40}} onClick={reset}>Current Month</Button></Grid></Grid></CardContent></Card>
 <Grid container spacing={2.5} mb={3}>{[["Selected month entries",rows.length],["Selected month expense",money(selectedTotal)],["All-time expense",money(allTotal)]].map(([l,v])=><Grid key={l} size={{xs:12,sm:4}}><Card><CardContent><Typography variant="body2" color="text.secondary">{l}</Typography><Typography variant="h5" mt={.7}>{v}</Typography></CardContent></Card></Grid>)}</Grid>
 <Grid container spacing={3}><Grid size={{xs:12,lg:4}}><Card><CardContent sx={{p:3}}><Stack direction="row" spacing={1.5} alignItems="center"><AddCardRoundedIcon color="primary"/><Box><Typography variant="h6">Add expense</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>Record a new business expense.</Typography></Box></Stack><Stack spacing={2} sx={{mt:2.5}}><TextField label="Expense Name" value={form.expense_name} onChange={e=>setForm({...form,expense_name:e.target.value})}/><TextField select label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Rent","Salary","Electricity","Transport","Internet","Purchase","Maintenance","Miscellaneous"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField type="number" label="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><TextField select label="Payment Mode" value={form.payment_mode} onChange={e=>setForm({...form,payment_mode:e.target.value})}>{["Cash","Online","Bank Transfer"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField type="date" label="Expense Date" InputLabelProps={{shrink:true}} value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/><TextField label="Note" multiline rows={2} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><Button variant="contained" onClick={save} disabled={saving}>{saving?"Saving...":"Save Expense"}</Button></Stack></CardContent></Card></Grid>
 <Grid size={{xs:12,lg:8}}><Card><CardContent sx={{p:0}}><Box sx={{p:3}}><Stack direction="row" spacing={1.5}><ReceiptRoundedIcon color="primary"/><Box><Typography variant="h6">Expense register</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>Showing records for {new Date(`${month}-01T00:00:00`).toLocaleDateString("en-IN",{month:"long",year:"numeric"})}.</Typography></Box></Stack></Box><TableContainer><Table><TableHead><TableRow><TableCell>Date</TableCell><TableCell>Expense</TableCell><TableCell>Category</TableCell><TableCell>Payment</TableCell><TableCell align="right">Amount</TableCell><TableCell align="center">Action</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.id} hover><TableCell>{new Date(r.expense_date).toLocaleDateString("en-GB")}</TableCell><TableCell><Typography fontWeight={700}>{r.expense_name}</Typography><Typography variant="caption" color="text.secondary">{r.note||"—"}</Typography></TableCell><TableCell><Chip size="small" label={r.category}/></TableCell><TableCell>{r.payment_mode}</TableCell><TableCell align="right"><Typography fontWeight={800}>{money(r.amount)}</Typography></TableCell><TableCell align="center"><Tooltip title="Delete"><IconButton color="error" onClick={()=>remove(r.id)}><DeleteOutlineRoundedIcon/></IconButton></Tooltip></TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={6}><Box sx={{py:7,textAlign:"center"}}><Typography fontWeight={700}>No expenses in selected month</Typography></Box></TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card></Grid></Grid></AppLayout>}
