import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, InputAdornment, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from "@mui/material";
import AddBoxRoundedIcon from "@mui/icons-material/AddBoxRounded";
import Inventory2RoundedIcon from "@mui/icons-material/Inventory2Rounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import UploadFileRoundedIcon from "@mui/icons-material/UploadFileRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import AppLayout from "../components/AppLayout";
import PageHeader from "../components/PageHeader";
import { addItem, deleteItem, getItems, importItems, updateItem } from "../services/api";
const money = (v) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(v || 0));
const emptyForm={item_name:"",barcode:"",purchase_price:"",mrp:"",sale_price:"",gst_percent:"",stock:""};
export default function Items(){
 const[items,setItems]=useState([]),[search,setSearch]=useState(""),[message,setMessage]=useState({type:"",text:""}),[saving,setSaving]=useState(false),[editing,setEditing]=useState(null);const[form,setForm]=useState(emptyForm);const fileRef=useRef();
 const load=async()=>{try{setItems(await getItems())}catch(e){setMessage({type:"error",text:e.message})}};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.item_name} ${x.barcode}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const payload=()=>({...form,purchase_price:Number(form.purchase_price),mrp:Number(form.mrp),sale_price:Number(form.sale_price),gst_percent:Number(form.gst_percent||0),stock:Number(form.stock||0)});
 const save=async()=>{if(!form.item_name||!form.barcode)return setMessage({type:"warning",text:"Item name and barcode are required."});try{setSaving(true);if(editing)await updateItem(editing.id,payload());else await addItem(payload());setForm(emptyForm);setEditing(null);await load();setMessage({type:"success",text:editing?"Item updated successfully.":"Item added successfully."})}catch(e){setMessage({type:"error",text:e.message})}finally{setSaving(false)}};
 const edit=(x)=>{setEditing(x);setForm({item_name:x.item_name,barcode:x.barcode,purchase_price:x.purchase_price,mrp:x.mrp,sale_price:x.sale_price,gst_percent:x.gst_percent,stock:x.stock})};
 const remove=async(x)=>{if(!confirm(`Delete ${x.item_name}?`))return;try{await deleteItem(x.id);await load();setMessage({type:"success",text:"Item deleted successfully."})}catch(e){setMessage({type:"error",text:e.message})}};
 const onImport=async(e)=>{const file=e.target.files?.[0];if(!file)return;try{const data=await file.arrayBuffer();const wb=XLSX.read(data);const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const normalized=rows.map(r=>({item_name:String(r.item_name||r["Item Name"]||"").trim(),barcode:String(r.barcode||r.Barcode||"").trim(),purchase_price:Number(r.purchase_price||r["Purchase Price"]||0),mrp:Number(r.mrp||r.MRP||r["MRP Price"]||r.sale_price||r["Sale Price"]||0),sale_price:Number(r.sale_price||r["Sale Price"]||0),gst_percent:Number(r.gst_percent||r["GST %"]||0),stock:Number(r.stock||r.Stock||0)})).filter(r=>r.item_name&&r.barcode);if(!normalized.length)throw new Error("No valid rows found. Use columns: item_name, barcode, purchase_price, mrp, sale_price, gst_percent, stock.");const result=await importItems(normalized);await load();setMessage({type:"success",text:`${result.created} items imported. ${result.skipped?.length||0} duplicate barcodes skipped.`})}catch(err){setMessage({type:"error",text:err.message})}finally{e.target.value=""}};
 const low=items.filter(x=>Number(x.stock)<=5&&Number(x.stock)>0).length,out=items.filter(x=>Number(x.stock)<=0).length,value=items.reduce((s,x)=>s+Number(x.purchase_price||0)*Number(x.stock||0),0);
 return <AppLayout><PageHeader title="Items & Stock" subtitle="Manage products, pricing, GST and inventory availability" />{message.text&&<Alert severity={message.type} sx={{mb:2.5}}>{message.text}</Alert>}
 <Grid container spacing={2.5} mb={3}>{[["Total products",items.length],["Low stock",low],["Out of stock",out],["Stock value",money(value)]].map(([l,v])=><Grid key={l} size={{xs:12,sm:6,lg:3}}><Card><CardContent><Typography variant="body2" color="text.secondary">{l}</Typography><Typography variant="h5" mt={.7}>{v}</Typography></CardContent></Card></Grid>)}</Grid>
 <Grid container spacing={3}><Grid size={{xs:12,xl:4}}><Card><CardContent sx={{p:3}}><Stack direction="row" spacing={1.5} alignItems="center" sx={{mb:3}}><Box sx={{width:42,height:42,borderRadius:2.5,bgcolor:"primary.light",color:"primary.main",display:"grid",placeItems:"center"}}><AddBoxRoundedIcon/></Box><Box><Typography variant="h6">{editing?"Edit inventory item":"Add inventory item"}</Typography><Typography variant="body2" color="text.secondary">Enter product and stock information.</Typography></Box></Stack><Grid container spacing={2}>{[["Item Name","item_name"],["Barcode","barcode"],["Purchase Price","purchase_price","number"],["MRP","mrp","number"],["Sale Price","sale_price","number"],["GST %","gst_percent","number"],["Opening Stock","stock","number"]].map(([l,k,t])=><Grid key={k} size={{xs:12,sm:k==="item_name"||k==="barcode"?12:6}}><TextField type={t||"text"} label={l} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Grid>)}</Grid><Button fullWidth variant="contained" onClick={save} disabled={saving} sx={{mt:2.5}}>{saving?"Saving...":editing?"Update Item":"Save Item"}</Button>{editing&&<Button fullWidth sx={{mt:1}} onClick={()=>{setEditing(null);setForm(emptyForm)}}>Cancel Edit</Button>}<input hidden ref={fileRef} type="file" accept=".xlsx,.xls,.csv" onChange={onImport}/><Button fullWidth variant="outlined" startIcon={<UploadFileRoundedIcon/>} sx={{mt:1.25}} onClick={()=>fileRef.current?.click()}>Import Excel / CSV</Button></CardContent></Card></Grid>
 <Grid size={{xs:12,xl:8}}><Card><CardContent sx={{p:0}}><Box sx={{p:3,display:"flex",justifyContent:"space-between",gap:2,flexDirection:{xs:"column",sm:"row"}}}><Box><Typography variant="h6">Inventory catalogue</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>Search, edit and maintain stock records.</Typography></Box><TextField sx={{maxWidth:320}} placeholder="Search item or barcode" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><SearchRoundedIcon/></InputAdornment>}}/></Box><TableContainer><Table><TableHead><TableRow><TableCell>Product</TableCell><TableCell>Barcode</TableCell><TableCell align="right">MRP</TableCell><TableCell align="right">Sale</TableCell><TableCell align="center">GST</TableCell><TableCell align="center">Stock</TableCell><TableCell align="center">Actions</TableCell></TableRow></TableHead><TableBody>{filtered.map(x=><TableRow key={x.id} hover><TableCell><Typography fontWeight={700}>{x.item_name}</Typography><Typography variant="caption" color="text.secondary">Purchase {money(x.purchase_price)}</Typography></TableCell><TableCell>{x.barcode}</TableCell><TableCell align="right">{money(x.mrp)}</TableCell><TableCell align="right"><Typography fontWeight={700}>{money(x.sale_price)}</Typography></TableCell><TableCell align="center">{x.gst_percent}%</TableCell><TableCell align="center"><Chip size="small" label={x.stock} color={Number(x.stock)<=0?"error":Number(x.stock)<=5?"warning":"success"}/></TableCell><TableCell align="center"><Tooltip title="Edit"><IconButton onClick={()=>edit(x)}><EditRoundedIcon/></IconButton></Tooltip><Tooltip title="Delete"><IconButton color="error" onClick={()=>remove(x)}><DeleteOutlineRoundedIcon/></IconButton></Tooltip></TableCell></TableRow>)}{!filtered.length&&<TableRow><TableCell colSpan={7}><Box sx={{py:7,textAlign:"center"}}><Typography fontWeight={700}>No inventory items found</Typography></Box></TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card></Grid></Grid></AppLayout>
}
