import { useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Grid, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import TrendingUpRoundedIcon from "@mui/icons-material/TrendingUpRounded";
import PaymentsRoundedIcon from "@mui/icons-material/PaymentsRounded";
import CreditCardRoundedIcon from "@mui/icons-material/CreditCardRounded";
import ReceiptLongRoundedIcon from "@mui/icons-material/ReceiptLongRounded";
import AppLayout from "../components/AppLayout";
import PageHeader from "../components/PageHeader";
import { getSalesReport } from "../services/api";
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`};
export default function SalesReport(){
 const[report,setReport]=useState({total_sales:0,cash_sales:0,online_sales:0,credit_sales:0,total_gst:0,total_bills:0,sales:[]});
 const[filters,setFilters]=useState({from_date:monthStart(),to_date:today(),payment_mode:"All"}); const[error,setError]=useState(""); const[loading,setLoading]=useState(false);
 const load=async()=>{try{setLoading(true);setError("");setReport(await getSalesReport(filters.from_date,filters.to_date,filters.payment_mode))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const reset=()=>{const next={from_date:monthStart(),to_date:today(),payment_mode:"All"};setFilters(next);getSalesReport(next.from_date,next.to_date,next.payment_mode).then(setReport).catch(e=>setError(e.message));};
 const cards=[["Total Sales",report.total_sales,<TrendingUpRoundedIcon/>],["Cash Sales",report.cash_sales,<PaymentsRoundedIcon/>],["Online Sales",report.online_sales,<CreditCardRoundedIcon/>],["Credit Sales",report.credit_sales,<ReceiptLongRoundedIcon/>]];
 return <AppLayout><PageHeader title="Sales Report" subtitle="Review date-wise invoices, collections and payment-mode performance" />{error&&<Alert severity="error" sx={{mb:2.5}}>{error}</Alert>}
 <Card sx={{mb:3}}><CardContent sx={{p:3}}><Typography variant="h6">Report filters</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5,mb:2.5}}>Select a date range and payment mode to review sales.</Typography><Grid container spacing={2} alignItems="center"><Grid size={{xs:12,md:3}}><TextField fullWidth type="date" label="From Date" InputLabelProps={{shrink:true}} value={filters.from_date} onChange={e=>setFilters({...filters,from_date:e.target.value})}/></Grid><Grid size={{xs:12,md:3}}><TextField fullWidth type="date" label="To Date" InputLabelProps={{shrink:true}} value={filters.to_date} onChange={e=>setFilters({...filters,to_date:e.target.value})}/></Grid><Grid size={{xs:12,md:3}}><TextField fullWidth select label="Payment Mode" value={filters.payment_mode} onChange={e=>setFilters({...filters,payment_mode:e.target.value})}>{["All","Cash","Online","Credit"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:3}}><Stack direction="row" spacing={1}><Button fullWidth variant="contained" onClick={load} disabled={loading}>{loading?"Loading...":"Apply Filter"}</Button><Button fullWidth variant="outlined" onClick={reset}>Reset</Button></Stack></Grid></Grid></CardContent></Card>
 <Grid container spacing={2.5} mb={3}>{cards.map(([l,v,i],idx)=><Grid key={l} size={{xs:12,sm:6,lg:3}}><Card><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="body2" color="text.secondary">{l}</Typography><Typography variant="h5" mt={.7}>{money(v)}</Typography></Box><Box sx={{width:42,height:42,borderRadius:2.5,bgcolor:["primary.light","#DCFCE7","#EDE9FE","#FFF7ED"][idx],display:"grid",placeItems:"center"}}>{i}</Box></Stack></CardContent></Card></Grid>)}</Grid>
 <Card><CardContent sx={{p:0}}><Box sx={{p:3,display:"flex",justifyContent:"space-between"}}><Box><Typography variant="h6">Invoice register</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>{report.total_bills} bills · GST {money(report.total_gst)}</Typography></Box><Chip label={`${report.sales.length} records`} color="primary" variant="outlined"/></Box><TableContainer><Table><TableHead><TableRow><TableCell>Date</TableCell><TableCell>Invoice</TableCell><TableCell>Customer</TableCell><TableCell>Mobile</TableCell><TableCell>Payment</TableCell><TableCell align="right">Amount</TableCell></TableRow></TableHead><TableBody>{report.sales.map(s=><TableRow key={s.id} hover><TableCell>{s.bill_date?new Date(`${s.bill_date}T00:00:00`).toLocaleDateString("en-GB"):"—"}</TableCell><TableCell><Typography fontWeight={800} color="primary.main">{s.invoice_no}</Typography></TableCell><TableCell>{s.customer_name||"Walk-in Customer"}</TableCell><TableCell>{s.customer_mobile||"—"}</TableCell><TableCell><Chip size="small" label={s.payment_mode} color={s.payment_mode==="Credit"?"warning":s.payment_mode==="Online"?"secondary":"success"} variant="outlined"/></TableCell><TableCell align="right"><Typography fontWeight={800}>{money(s.final_amount)}</Typography></TableCell></TableRow>)}{!report.sales.length&&<TableRow><TableCell colSpan={6}><Box sx={{py:7,textAlign:"center"}}><Typography fontWeight={700}>No sales found for selected dates</Typography></Box></TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card></AppLayout>
}
