import { useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Grid, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import BusinessRoundedIcon from "@mui/icons-material/BusinessRounded";
import PersonRoundedIcon from "@mui/icons-material/PersonRounded";
import LockResetRoundedIcon from "@mui/icons-material/LockResetRounded";
import SaveRoundedIcon from "@mui/icons-material/SaveRounded";
import AppLayout from "../components/AppLayout";
import PageHeader from "../components/PageHeader";
import { getSettings, updatePassword, updateSettings, updateUsername } from "../services/api";

export default function Settings(){
 const user=JSON.parse(localStorage.getItem("user"))||{};const userId=user.user_id||"admin";const[tab,setTab]=useState(0);const[message,setMessage]=useState({type:"",text:""});const[loading,setLoading]=useState(false);
 const[business,setBusiness]=useState({business_name:"",email:"",mobile:"",gst_number:"",address:""});const[username,setUsername]=useState({new_user_id:""});const[password,setPassword]=useState({old_password:"",new_password:"",confirm_password:""});
 useEffect(()=>{getSettings(userId).then(d=>{setBusiness({business_name:d.business_name||"",email:d.email||"",mobile:d.mobile||"",gst_number:d.gst_number||"",address:d.address||""});setUsername({new_user_id:d.user_id||userId});}).catch(e=>setMessage({type:"error",text:e.message}));},[userId]);
 const saveBusiness=async()=>{try{setLoading(true);await updateSettings(userId,business);setMessage({type:"success",text:"Business profile updated successfully."});}catch(e){setMessage({type:"error",text:e.message});}finally{setLoading(false)}};
 const saveUsername=async()=>{if(!username.new_user_id)return setMessage({type:"warning",text:"Enter a new username."});try{await updateUsername(userId,username);alert("Username updated. Please login again.");localStorage.removeItem("user");window.location.href="/";}catch(e){setMessage({type:"error",text:e.message})}};
 const savePassword=async()=>{if(!password.old_password||!password.new_password)return setMessage({type:"warning",text:"Enter old and new password."});if(password.new_password!==password.confirm_password)return setMessage({type:"warning",text:"New password and confirmation do not match."});try{await updatePassword(userId,{old_password:password.old_password,new_password:password.new_password});setPassword({old_password:"",new_password:"",confirm_password:""});setMessage({type:"success",text:"Password changed successfully."});}catch(e){setMessage({type:"error",text:e.message})}};
 const panel=[
  <Grid container spacing={3} key="business"><Grid size={{xs:12,lg:8}}><Card><CardContent sx={{p:3}}><Stack direction="row" spacing={1.5} alignItems="center" mb={3}><Box sx={{width:44,height:44,borderRadius:2.5,bgcolor:"primary.light",color:"primary.main",display:"grid",placeItems:"center"}}><BusinessRoundedIcon/></Box><Box><Typography variant="h6">Business profile</Typography><Typography variant="body2" color="text.secondary">Information displayed on invoices and reports.</Typography></Box></Stack><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField label="Business Name" value={business.business_name} onChange={e=>setBusiness({...business,business_name:e.target.value})}/></Grid><Grid size={{xs:12,md:6}}><TextField label="GST Number" value={business.gst_number} onChange={e=>setBusiness({...business,gst_number:e.target.value})}/></Grid><Grid size={{xs:12,md:6}}><TextField label="Business Email" value={business.email} onChange={e=>setBusiness({...business,email:e.target.value})}/></Grid><Grid size={{xs:12,md:6}}><TextField label="Mobile Number" value={business.mobile} onChange={e=>setBusiness({...business,mobile:e.target.value})}/></Grid><Grid size={{xs:12}}><TextField multiline rows={4} label="Business Address" value={business.address} onChange={e=>setBusiness({...business,address:e.target.value})}/></Grid></Grid><Button variant="contained" startIcon={<SaveRoundedIcon/>} onClick={saveBusiness} disabled={loading} sx={{mt:2.5}}>{loading?"Saving...":"Save Business Profile"}</Button></CardContent></Card></Grid><Grid size={{xs:12,lg:4}}><Card><CardContent sx={{p:3}}><Typography variant="h6">Invoice identity</Typography><Typography variant="body2" color="text.secondary" mt={1}>These details will be used as your company identity across bills, reports and customer statements.</Typography><Box sx={{mt:3,p:2.5,borderRadius:3,bgcolor:"#F8FAFC",border:"1px dashed #CBD5E1"}}><Typography variant="caption" color="text.secondary">BUSINESS NAME</Typography><Typography fontWeight={800} mt={.5}>{business.business_name||"Your Business"}</Typography><Typography variant="body2" color="text.secondary" mt={1}>{business.gst_number||"GST number not configured"}</Typography><Typography variant="body2" color="text.secondary">{business.mobile||"Mobile not configured"}</Typography><Typography variant="body2" color="text.secondary">{business.email||"Email not configured"}</Typography></Box></CardContent></Card></Grid></Grid>,
  <Grid container spacing={3} key="account"><Grid size={{xs:12,md:6}}><Card><CardContent sx={{p:3}}><Stack direction="row" spacing={1.5} alignItems="center" mb={3}><PersonRoundedIcon color="primary"/><Box><Typography variant="h6">Login UserName</Typography><Typography variant="body2" color="text.secondary">Change the username used to sign in.</Typography></Box></Stack><TextField label="New Username" value={username.new_user_id} onChange={e=>setUsername({new_user_id:e.target.value})}/><Button fullWidth variant="contained" onClick={saveUsername} sx={{mt:2}}>Update Username</Button></CardContent></Card></Grid><Grid size={{xs:12,md:6}}><Card><CardContent sx={{p:3}}><Stack direction="row" spacing={1.5} alignItems="center" mb={3}><LockResetRoundedIcon color="warning"/><Box><Typography variant="h6">Account security</Typography><Typography variant="body2" color="text.secondary">Use a strong, unique password.</Typography></Box></Stack><Stack spacing={2}><TextField type="password" label="Current Password" value={password.old_password} onChange={e=>setPassword({...password,old_password:e.target.value})}/><TextField type="password" label="New Password" value={password.new_password} onChange={e=>setPassword({...password,new_password:e.target.value})}/><TextField type="password" label="Confirm New Password" value={password.confirm_password} onChange={e=>setPassword({...password,confirm_password:e.target.value})}/><Button color="warning" variant="contained" onClick={savePassword}>Change Password</Button></Stack></CardContent></Card></Grid></Grid>
 ];
 return <AppLayout><PageHeader title="Settings" subtitle="Configure business identity, login account and security" />{message.text&&<Alert severity={message.type} sx={{mb:2.5}}>{message.text}</Alert>}<Card sx={{mb:3}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto" sx={{px:2}}><Tab icon={<BusinessRoundedIcon/>} iconPosition="start" label="Business Profile"/><Tab icon={<PersonRoundedIcon/>} iconPosition="start" label="Account & Security"/></Tabs></Card>{panel[tab]}</AppLayout>
}
