import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, InputAdornment, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import InventoryRoundedIcon from "@mui/icons-material/InventoryRounded";
import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";
import EditNoteRoundedIcon from "@mui/icons-material/EditNoteRounded";
import AppLayout from "../components/AppLayout";
import PageHeader from "../components/PageHeader";
import { bulkUpdateItems, getStockReport } from "../services/api";
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v||0));
export default function StockReport(){
 const[items,setItems]=useState([]),[rows,setRows]=useState([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const load=async()=>{try{setItems(await getStockReport());setError("")}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.item_name} ${x.barcode}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const units=items.reduce((s,x)=>s+Number(x.stock||0),0),low=items.filter(x=>Number(x.stock)<=5).length,value=items.reduce((s,x)=>s+Number(x.purchase_price||0)*Number(x.stock||0),0);
 const startBulk=()=>{setRows(items.map(x=>({...x,stock_adjustment:0,adjustment_reason:"Stock Received",_dirty:false})));setOpen(true)};
 const change=(id,key,value)=>setRows(r=>r.map(x=>x.id===id?{...x,[key]:value,_dirty:true}:x));
 const invalid=rows.some(r=>Number(r.sale_price)>Number(r.mrp)||Number(r.mrp)<0||Number(r.purchase_price)<0||Number(r.sale_price)<0||Number(r.stock)+Number(r.stock_adjustment||0)<0||!r.item_name||!r.barcode);
 const changed=rows.filter(r=>r._dirty);
 const save=async()=>{if(!changed.length)return setOpen(false);try{setSaving(true);await bulkUpdateItems(changed.map(({_dirty,stock,...r})=>({...r,purchase_price:Number(r.purchase_price),mrp:Number(r.mrp),sale_price:Number(r.sale_price),gst_percent:Number(r.gst_percent),stock_adjustment:Number(r.stock_adjustment||0)})));setOpen(false);setMessage(`${changed.length} products updated successfully.`);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <AppLayout><PageHeader title="Stock Report" subtitle="Monitor inventory quantity, valuation and update products directly on screen" />{error&&<Alert severity="error" sx={{mb:2.5}}>{error}</Alert>}{message&&<Alert severity="success" sx={{mb:2.5}}>{message}</Alert>}
 <Grid container spacing={2.5} mb={3}>{[["Inventory items",items.length,<InventoryRoundedIcon color="primary"/>],["Units in stock",units,<InventoryRoundedIcon color="success"/>],["Low stock alerts",low,<WarningAmberRoundedIcon color="warning"/>],["Stock valuation",money(value),null]].map(([l,v,i])=><Grid key={l} size={{xs:12,sm:6,lg:3}}><Card><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="body2" color="text.secondary">{l}</Typography><Typography variant="h5" mt={.5}>{v}</Typography></Box>{i}</Stack></CardContent></Card></Grid>)}</Grid>
 <Card><CardContent sx={{p:0}}><Box sx={{p:3,display:"flex",justifyContent:"space-between",gap:2,flexDirection:{xs:"column",sm:"row"}}}><Box><Typography variant="h6">Inventory position</Typography><Typography variant="body2" color="text.secondary">Detailed stock, MRP and selling-price information.</Typography></Box><Stack direction={{xs:"column",sm:"row"}} spacing={1.5}><TextField sx={{maxWidth:320}} placeholder="Search item or barcode" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><SearchRoundedIcon/></InputAdornment>}}/><Button variant="contained" startIcon={<EditNoteRoundedIcon/>} onClick={startBulk}>Bulk Update</Button></Stack></Box>
 <TableContainer><Table><TableHead><TableRow><TableCell>Item</TableCell><TableCell>Barcode</TableCell><TableCell align="right">Purchase</TableCell><TableCell align="right">MRP</TableCell><TableCell align="right">Sales Price</TableCell><TableCell align="center">GST</TableCell><TableCell align="center">Stock</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{filtered.map(x=><TableRow key={x.id} hover><TableCell><Typography fontWeight={700}>{x.item_name}</Typography></TableCell><TableCell>{x.barcode}</TableCell><TableCell align="right">{money(x.purchase_price)}</TableCell><TableCell align="right">{money(x.mrp)}</TableCell><TableCell align="right">{money(x.sale_price)}</TableCell><TableCell align="center">{x.gst_percent}%</TableCell><TableCell align="center"><Typography fontWeight={800}>{x.stock}</Typography></TableCell><TableCell><Chip size="small" label={Number(x.stock)<=5?"Low Stock":"In Stock"} color={Number(x.stock)<=5?"warning":"success"}/></TableCell></TableRow>)}{!filtered.length&&<TableRow><TableCell colSpan={8} align="center" sx={{py:7}}>No stock records found</TableCell></TableRow>}</TableBody></Table></TableContainer></CardContent></Card>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="xl"><DialogTitle>Bulk Product Update</DialogTitle><DialogContent dividers><Alert severity="info" sx={{mb:2}}>Edit values directly in the table. Only changed rows will be saved. Sales Price cannot exceed MRP.</Alert><TableContainer sx={{maxHeight:"65vh"}}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>Product</TableCell><TableCell>Barcode</TableCell><TableCell>Purchase</TableCell><TableCell>MRP</TableCell><TableCell>Sales Price</TableCell><TableCell>GST %</TableCell><TableCell>Current</TableCell><TableCell>Adjust</TableCell><TableCell>New Stock</TableCell><TableCell>Reason</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.id} sx={{bgcolor:r._dirty?"action.hover":undefined}}><TableCell><TextField size="small" value={r.item_name} onChange={e=>change(r.id,"item_name",e.target.value)}/></TableCell><TableCell><TextField size="small" value={r.barcode} onChange={e=>change(r.id,"barcode",e.target.value)}/></TableCell>{["purchase_price","mrp","sale_price","gst_percent"].map(k=><TableCell key={k}><TextField size="small" type="number" value={r[k]} error={k==="sale_price"&&Number(r.sale_price)>Number(r.mrp)} onChange={e=>change(r.id,k,e.target.value)} sx={{width:105}}/></TableCell>)}<TableCell align="center">{r.stock}</TableCell><TableCell><TextField size="small" type="number" value={r.stock_adjustment} onChange={e=>change(r.id,"stock_adjustment",e.target.value)} sx={{width:90}}/></TableCell><TableCell align="center"><Typography fontWeight={800} color={Number(r.stock)+Number(r.stock_adjustment||0)<0?"error.main":"text.primary"}>{Number(r.stock)+Number(r.stock_adjustment||0)}</Typography></TableCell><TableCell><TextField select size="small" value={r.adjustment_reason} onChange={e=>change(r.id,"adjustment_reason",e.target.value)} sx={{minWidth:145}}>{["Stock Received","Damage","Return","Correction","Other"].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></TableCell></TableRow>)}</TableBody></Table></TableContainer></DialogContent><DialogActions><Typography variant="body2" color="text.secondary" sx={{mr:"auto",pl:1}}>{changed.length} changed row(s)</Typography><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving||invalid||!changed.length} onClick={save}>{saving?"Saving...":"Save All Changes"}</Button></DialogActions></Dialog>
 </AppLayout>}
